name: Auto update data

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 12 * * 1'

jobs:
  auto-update:  
    name: Update Files  
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 

      - name: Download files
        run: |
          cd scripts
          python download_files_from_list.py
          
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add changes"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
